### PR TITLE
Support for Dependancy Injection

### PR DESCRIPTION
**Pull request by mumby0168**
This has got rid of the static class and simply but an interface behind the loading class. I have also created an extensions class so this can be added using the services collection. I have updated the sample project to suit.

### CODE REVIEW

**Comment by h3x4d3c1m4l** [comment]
Awesome! This is definitely an improvement. I will look into the details soon.

**Comment by mumby0168** [comment]
There is definetly some more refactoring we could do but its not essential. I will look at updating the readme as well if you are happy with the updates.

**Comment by h3x4d3c1m4l** [comment]
I noticed two things, which need to be addressed before merging:
- `Loading.cs` is still there, it is not needed anymore as DI is the recommended approach for this kind of library I think -> let's get rid of it?
- The `Samples.Template.Client` template is broken, I switches between the provided template and the default template... I'm not sure why yet as I don't have time to debug this at the moment :(

**Comment by mumby0168** [comment]
No problem this was done quickly I'll take a look when I get a spare half hour this week. Yes I agree get rid of the static loading file and I'll update the client template.

**Comment by mumby0168** [comment]
@h3x4d3c1m4l I made the changes to fix the issues and removed the redundant file.

**Comment by h3x4d3c1m4l** [comment]
Thanks!

**Pull request merged**
